export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";

export const FETCH_PRODUCTS_FULFILLED = "FETCH_PRODUCTS_FULFILLED";

export const FETCH_MORE_PRODUCTS_PENDING = "FETCH_MORE_PRODUCTS_PENDING";

export const FETCH_MORE_PRODUCTS_FULFILLED = "FETCH_MORE_PRODUCTS_FULFILLED";

export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
